version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 4000:4000
    volumes:
      - ./src:/folder/src

  database:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
